In [ ]:
# Info about dataset at https://opendata.dc.gov/datasets/computer-assisted-mass-appraisal-residential

In [74]:
import pandas as pd
import numpy as np
loc = 'datasets/DC_Properties.csv'
dcdf = pd.read_csv(loc, index_col=0)
dcdf.head()

BATHRM  HF_BATHRM           HEAT AC  NUM_UNITS  ROOMS  BEDRM     AYB  \
0       4          0      Warm Cool  Y        2.0      8      4  1910.0   
1       3          1      Warm Cool  Y        2.0     11      5  1898.0   
2       3          1  Hot Water Rad  Y        2.0      9      5  1910.0   
3       3          1  Hot Water Rad  Y        2.0      8      5  1900.0   
4       2          1      Warm Cool  Y        1.0     11      3  1913.0   

   YR_RMDL   EYB   ...     LONGITUDE ASSESSMENT_NBHD  ASSESSMENT_SUBNBHD  \
0   1988.0  1972   ...    -77.040832      Old City 2    040 D Old City 2   
1   2007.0  1972   ...    -77.040764      Old City 2    040 D Old City 2   
2   2009.0  1984   ...    -77.040678      Old City 2    040 D Old City 2   
3   2003.0  1984   ...    -77.040629      Old City 2    040 D Old City 2   
4   2012.0  1985   ...    -77.039361      Old City 2    040 D Old City 2   

  CENSUS_TRACT  CENSUS_BLOCK    WARD  SQUARE          X          Y QUADRANT  
0       4201.0   004201 2006  Ward 2     152 -77.040429  38.914881       NW  
1       4201.0   004201 2006  Ward 2     152 -77.040429  38.914881       NW  
2       4201.0   004201 2006  Ward 2     152 -77.040429  38.914881       NW  
3       4201.0   004201 2006  Ward 2     152 -77.040429  38.914881       NW  
4       4201.0   004201 2006  Ward 2     152 -77.040429  38.914881       NW  

[5 rows x 48 columns]

In [75]:
dcdf.dtypes

BATHRM                  int64
HF_BATHRM               int64
HEAT                   object
AC                     object
NUM_UNITS             float64
ROOMS                   int64
BEDRM                   int64
AYB                   float64
YR_RMDL               float64
EYB                     int64
STORIES               float64
SALEDATE               object
PRICE                 float64
QUALIFIED              object
SALE_NUM                int64
GBA                   float64
BLDG_NUM                int64
STYLE                  object
STRUCT                 object
GRADE                  object
CNDTN                  object
EXTWALL                object
ROOF                   object
INTWALL                object
KITCHENS              float64
FIREPLACES              int64
USECODE                 int64
LANDAREA                int64
GIS_LAST_MOD_DTTM      object
SOURCE                 object
CMPLX_NUM             float64
LIVING_GBA            float64
FULLADDRESS            object
CITY      

In [76]:
dcdf.count()

BATHRM                158957
HF_BATHRM             158957
HEAT                  158957
AC                    158957
NUM_UNITS             106696
ROOMS                 158957
BEDRM                 158957
AYB                   158686
YR_RMDL                80928
EYB                   158957
STORIES               106652
SALEDATE              132187
PRICE                  98216
QUALIFIED             158957
SALE_NUM              158957
GBA                   106696
BLDG_NUM              158957
STYLE                 106696
STRUCT                106696
GRADE                 106696
CNDTN                 106696
EXTWALL               106696
ROOF                  106696
INTWALL               106696
KITCHENS              106695
FIREPLACES            158957
USECODE               158957
LANDAREA              158957
GIS_LAST_MOD_DTTM     158957
SOURCE                158957
CMPLX_NUM              52261
LIVING_GBA             52261
FULLADDRESS           106040
CITY                  106051
STATE         

In [77]:
dcdf.duplicated()

0         False
1         False
2         False
3         False
4         False
5         False
6         False
7         False
8         False
9         False
10        False
11        False
12        False
13        False
14        False
15        False
16        False
17        False
18        False
19        False
20        False
21        False
22        False
23        False
24        False
25        False
26        False
27        False
28        False
29        False
          ...  
158927    False
158928    False
158929    False
158930    False
158931    False
158932    False
158933    False
158934    False
158935    False
158936    False
158937    False
158938    False
158939    False
158940    False
158941    False
158942    False
158943    False
158944    False
158945    False
158946    False
158947    False
158948    False
158949    False
158950    False
158951    False
158952    False
158953    False
158954    False
158955    False
158956    False
Length: 158957, dtype: b

In [80]:
# Checking values in data
dcdf['BATHRM'].unique()

array([ 4,  3,  2,  1,  5,  6,  7,  8, 11,  9,  0, 10, 12, 14, 13])

In [81]:
dcdf['HF_BATHRM'].unique()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  9, 11])

In [82]:
dcdf['HEAT'].unique()

array(['Warm Cool', 'Hot Water Rad', 'Forced Air', 'Elec Base Brd',
       'Ht Pump', 'Electric Rad', 'Wall Furnace', 'Water Base Brd',
       'Evp Cool', 'Air Exchng', 'No Data', 'Ind Unit', 'Gravity Furnac',
       'Air-Oil'], dtype=object)

In [83]:
dcdf['AC'].unique()

array(['Y', 'N', '0'], dtype=object)

In [85]:
dcdf['NUM_UNITS'].unique()

array([ 2.,  1.,  3.,  4.,  5.,  0.,  6., nan])

In [86]:
dcdf['ROOMS'].unique()

array([ 8, 11,  9, 10,  5,  7,  6, 12, 16, 14, 13,  4, 15, 18, 20, 19, 17,
        0,  3, 21, 25, 23,  2,  1, 31, 41, 27, 39, 22, 32, 28, 48, 37, 34,
       26, 24, 40, 29, 35, 30])

In [87]:
dcdf['BEDRM'].unique()

array([ 4,  5,  3,  2,  6,  7,  1,  8,  9, 10, 11,  0, 20, 12, 16, 24, 13,
       15, 19, 14])

In [88]:
dcdf['YR_RMDL'].unique()

array([1988., 2007., 2009., 2003., 2012.,   nan, 2011., 2008., 1979.,
       1950., 2000., 1990., 2006., 1987., 2013., 2010., 2004., 1963.,
       1960., 2014., 1975., 1978., 2016., 1974., 1980., 2002., 1999.,
       2005., 2001., 2015., 1935., 1995., 1984., 1973., 1996., 1976.,
       1985., 1998., 1968., 1956., 1954., 1991., 1941., 1992., 1966.,
       2018., 1925., 1997., 1959., 1989., 2017., 1951., 1948., 1982.,
       1977., 1983., 1972., 1981., 1971., 1965., 1962., 1967., 1994.,
       1955., 1986., 1964., 1949., 1969., 1993., 1961., 1924., 1922.,
       1952., 1916., 1970., 1945., 1958., 1947., 1940., 1944., 1928.,
       1939., 1957., 1953., 1929., 1923., 1915., 1900., 1926., 1946.,
       1936., 1927., 1880., 1943., 1934., 1942., 1938., 1930., 1937.,
       1932., 1920., 1933., 1931., 1913., 1911., 1921.,   20., 2019.,
       1917., 1912., 1910.])

In [89]:
dcdf['STORIES'].unique()

array([3.00e+00, 4.00e+00, 2.00e+00, 2.50e+00, 2.25e+00, 3.50e+00,
       1.00e+00,      nan, 3.25e+00, 1.50e+00, 2.75e+00, 7.00e+00,
       6.50e+01, 2.70e+00, 0.00e+00, 8.26e+02, 6.00e+00, 2.30e+00,
       5.00e+00, 2.20e+00, 3.70e+00, 1.70e+00, 3.20e+00, 1.75e+00,
       3.75e+00, 4.50e+00, 2.50e+02, 2.75e+02, 1.25e+00, 2.50e+01,
       4.75e+00, 9.00e+00, 5.00e-01, 8.25e+00, 7.50e-01, 2.33e+00,
       2.00e+01, 1.20e+01, 4.30e+01, 1.34e+00, 2.50e-01])

In [90]:
dcdf['QUALIFIED'].unique()

array(['Q', 'U'], dtype=object)

In [91]:
dcdf['SALE_NUM'].unique()

array([ 1,  3,  4,  6,  2,  5,  7,  9, 10,  8, 11, 12, 14, 13, 15])

In [92]:
dcdf['STYLE'].unique()

array(['3 Story', '4 Story', '2 Story', '2.5 Story Fin', '3.5 Story Fin',
       '1 Story', '1.5 Story Fin', '2.5 Story Unfin', '3.5 Story Unfin',
       'Default', '1.5 Story Unfin', '4.5 Story Fin', 'Split Level',
       'Bi-Level', 'Split Foyer', 'Vacant', 'Outbuildings',
       '4.5 Story Unfin', nan], dtype=object)

In [93]:
dcdf['STRUCT'].unique()

array(['Row Inside', 'Semi-Detached', 'Single', 'Row End', 'Multi',
       'Town Inside', 'Town End', 'Default', 'Vacant Land', nan],
      dtype=object)

In [94]:
dcdf['GRADE'].unique()

array(['Very Good', 'Above Average', 'Good Quality', 'Excellent',
       'Average', 'Superior', 'Fair Quality', 'Exceptional-D',
       'Exceptional-C', 'Low Quality', 'Exceptional-A', 'Exceptional-B',
       'No Data', nan], dtype=object)

In [95]:
dcdf['CNDTN'].unique()

array(['Good', 'Very Good', 'Average', 'Fair', 'Excellent', 'Poor',
       'Default', nan], dtype=object)

In [96]:
dcdf['EXTWALL'].unique()

array(['Common Brick', 'Brick/Stone', 'Stucco', 'Stone', 'Stucco Block',
       'Brick/Stucco', 'Concrete Block', 'Face Brick', 'Wood Siding',
       'Aluminum', 'Brick/Siding', 'Vinyl Siding', 'Stone Veneer',
       'Brick Veneer', 'Stone/Stucco', 'Stone/Siding', 'Metal Siding',
       'Shingle', 'Concrete', 'Plywood', 'Hardboard', 'Default', 'Adobe',
       'Rustic Log', 'SPlaster', nan], dtype=object)

In [97]:
dcdf['ROOF'].unique()

array(['Metal- Sms', 'Built Up', 'Neopren', 'Comp Shingle', 'Metal- Cpr',
       'Typical', 'Slate', 'Composition Ro', 'Metal- Pre', 'Shingle',
       'Concrete', 'Shake', 'Clay Tile', 'Water Proof', 'Concrete Tile',
       'Wood- FS', nan], dtype=object)

In [98]:
dcdf['INTWALL'].unique()

array(['Hardwood', 'Wood Floor', 'Hardwood/Carp', 'Carpet', 'Lt Concrete',
       'Vinyl Comp', 'Ceramic Tile', 'Default', 'Terrazo', 'Parquet',
       'Vinyl Sheet', 'Resiliant', nan], dtype=object)

In [99]:
dcdf['KITCHENS'].unique()

array([ 2.,  1.,  3.,  4.,  5.,  0.,  6., 44., nan])

In [100]:
dcdf['FIREPLACES'].unique()

array([     5,      4,      3,      0,      1,      2,      6,      7,
            8,     12,     10,     13,     11,      9,   1601,    922,
         4068,    200, 293920,   1017])

In [101]:
dcdf['USECODE'].unique()

array([ 24,  13,  11,  12,  23,  15,  39,  19,  81,  29,  83,  41,  16,
        17, 117, 116])

In [102]:
dcdf['SOURCE'].unique()

array(['Residential', 'Condominium'], dtype=object)

In [103]:
dcdf['CITY'].unique()

array(['WASHINGTON', nan], dtype=object)

In [104]:
dcdf['STATE'].unique()

array(['DC', nan], dtype=object)

In [105]:
dcdf['ZIPCODE'].unique()

array([20009., 20037., 20036., 20005., 20052., 20008., 20001., 20024.,
       20006., 20003., 20002., 20007., 20016., 20015., 20011., 20010.,
       20012., 20017., 20018., 20019., 20020., 20032.,    nan, 20392.,
       20004.])

In [106]:
dcdf['WARD'].unique()

array(['Ward 2', 'Ward 1', 'Ward 6', 'Ward 5', 'Ward 3', 'Ward 4',
       'Ward 7', 'Ward 8', nan], dtype=object)

In [107]:
dcdf['QUADRANT'].unique()

array(['NW', 'SW', 'SE', 'NE', nan], dtype=object)

In [108]:
dcdf['CENSUS_TRACT'].unique()

array([ 4201.,  5201.,  4300., 10800.,  5500.,  4202.,  5301.,  5600.,
        4400., 10700.,  5001.,  5002.,  4801.,  4802.,  4901.,  4702.,
        6400.,  4902., 10200.,  4600.,  4701.,  7200.,  8200.,  6500.,
        7000.,  8301., 11000., 10600.,  8302.,  6600.,  8100.,  8410.,
        8402.,  6700.,  6900.,  8001.,  8002.,  7100.,  6802.,  6801.,
         202.,   100.,  6804.,   300.,   702.,   802.,   801.,   902.,
         901.,  1001.,  1100.,  1002.,  1200.,   701.,   600.,  1500.,
        1302.,  1401.,   400.,  1402.,  1301.,   502.,  9505.,  4100.,
        4001.,   501.,  2701.,  3800.,  4002.,  2702.,  2600.,  3900.,
        2801.,  2502.,  2501.,  3700.,  2802.,  2001.,  1804.,  1803.,
        1600.,  2002.,  2900.,  3000.,  3100.,  3600.,  3500.,  1901.,
        2101.,  2201., 10300.,  2400.,  1702.,  3200.,  3400.,  3302.,
        3301.,  2102.,  2301.,  2202.,  1902.,  8701.,  9203.,  9501.,
        9204.,  9201.,  8702.,  9508.,  9507.,  9509.,  9504.,  9302.,
      

In [117]:
missing = dcdf['CITY'].isnull()
dcdf.loc[missing]

BATHRM  HF_BATHRM           HEAT AC  NUM_UNITS  ROOMS  BEDRM     AYB  \
1426         2          1     Forced Air  Y        1.0      6      4  1894.0   
1449         4          2     Forced Air  Y        2.0     10      4  2009.0   
1492         2          1     Forced Air  Y        1.0      4      2  1900.0   
2108         3          0      Warm Cool  Y        2.0      6      4  1890.0   
2109         3          1      Warm Cool  Y        2.0      8      4  1990.0   
2758         2          1  Hot Water Rad  N        2.0      8      3  1892.0   
3727         4          0  Hot Water Rad  N        4.0     16      7  1906.0   
3816         2          1     Forced Air  Y        1.0      6      2  1890.0   
3817         1          1  Hot Water Rad  Y        1.0      6      2  1890.0   
3862         3          1     Forced Air  Y        1.0      6      4  1900.0   
4034         3          0  Hot Water Rad  N        2.0     16      5     NaN   
4368         4          0        Ht Pump  Y        4.0      9      4  1900.0   
4798         2          0     Forced Air  Y        1.0      5      2  1880.0   
5341         2          1     Forced Air  Y        1.0      7      3  1890.0   
5802         4          0      Warm Cool  Y        4.0     12      4  1926.0   
6980         3          1     Forced Air  Y        2.0      6      5  1880.0   
7761         1          0     Forced Air  Y        1.0      4      2  1880.0   
9243         5          1     Forced Air  Y        1.0     12      5  2007.0   
9244         5          1      Warm Cool  Y        1.0     12      6  2007.0   
9245         5          1     Forced Air  Y        1.0     12      3  2007.0   
9563         2          1  Hot Water Rad  Y        1.0      6      3  1925.0   
11092        5          1        Ht Pump  Y        2.0      9      5  1920.0   
11213        2          1  Hot Water Rad  Y        1.0      7      3  1908.0   
11298        4          1     Forced Air  Y        1.0      8      3  1900.0   
11664        3          2     Forced Air  Y        2.0     11      3  1900.0   
12731        1          1  Hot Water Rad  Y        1.0      5      2  1900.0   
13282        2          1     Forced Air  Y        1.0      6      2  1900.0   
13933        1          0  Hot Water Rad  Y        1.0      6      3  1900.0   
14876        2          0      Warm Cool  Y        1.0     11      8  1908.0   
15971        4          0     Forced Air  Y        4.0     12      4  1927.0   
...        ...        ...            ... ..        ...    ...    ...     ...   
158927       2          0        Ht Pump  Y        NaN      6      3  1993.0   
158928       2          1        Ht Pump  Y        NaN      5      2  2013.0   
158929       2          1        Ht Pump  Y        NaN      5      2  2013.0   
158930       2          0     Forced Air  N        NaN      4      2  1900.0   
158931       2          1     Forced Air  N        NaN      4      2  1900.0   
158932       2          1     Forced Air  N        NaN      4      2  1900.0   
158933       2          0        Ht Pump  Y        NaN      4      2  1880.0   
158934       1          1        Ht Pump  Y        NaN      3      1  1880.0   
158935       1          0        Ht Pump  Y        NaN      3      1  1880.0   
158936       1          0        Ht Pump  Y        NaN      3      1  1880.0   
158937       1          0     Forced Air  Y        NaN      4      2  1992.0   
158938       2          0      Warm Cool  Y        NaN      7      4  1992.0   
158939       1          0     Forced Air  Y        NaN      4      2  1992.0   
158940       2          0     Forced Air  Y        NaN      7      4  1992.0   
158941       1          0     Forced Air  Y        NaN      4      2  1992.0   
158942       2          0     Forced Air  Y        NaN      7      4  1992.0   
158943       2          1     Forced Air  Y        NaN      5      2  2004.0   
158944       2          1     Forced Air  Y        NaN      5      2  2004.0   
158945  

In [121]:
missing = dcdf['QUADRANT'].isnull()
dcdf.loc[missing]

BATHRM  HF_BATHRM           HEAT AC  NUM_UNITS  ROOMS  BEDRM     AYB  \
104586       5          1      Warm Cool  Y        1.0     13      5  1930.0   
104587       3          1     Forced Air  Y        1.0      7      3  1952.0   
104588       4          0  Hot Water Rad  N        1.0     10      4  1953.0   
104589       3          0     Forced Air  Y        1.0     11      4  1958.0   
104590       3          2      Warm Cool  Y        1.0     16      4  1957.0   
104591       3          2      Warm Cool  Y        1.0     12      3  1957.0   
104592       4          1      Warm Cool  Y        1.0     10      5  1957.0   
104593       3          1  Hot Water Rad  N        1.0      9      3  1956.0   
104594       3          0      Warm Cool  Y        1.0      7      3  1960.0   
104595       3          0      Warm Cool  Y        1.0      9      3  1955.0   
104596       5          1      Warm Cool  Y        1.0     13      4  1957.0   
104597       3          1     Forced Air  Y        1.0     10      4  1955.0   
104598       2          1      Warm Cool  Y        1.0      8      3  1954.0   
104599       4          0      Warm Cool  Y        1.0      9      4  1954.0   
104600       3          0      Warm Cool  Y        1.0     11      4  1954.0   
104601       3          0      Warm Cool  Y        1.0     10      3  1955.0   
104602       2          2     Forced Air  Y        1.0     10      5  1955.0   
104603       1          4      Warm Cool  Y        1.0     10      4  1958.0   
104604       3          1  Hot Water Rad  Y        1.0      9      5  1916.0   
104605       2          1      Warm Cool  Y        1.0      9      3  1952.0   
104606       2          0  Hot Water Rad  N        1.0      6      4  1910.0   
104607       2          0  Hot Water Rad  N        1.0      6      2  1922.0   
104608       4          0  Hot Water Rad  N        4.0     16      4  1940.0   
104609       3          0      Warm Cool  Y        1.0      7      4  1947.0   
104610       2          0  Hot Water Rad  N        2.0     11      4  1938.0   
104611       2          1      Warm Cool  Y        1.0      6      3  1900.0   
104612       2          1      Warm Cool  Y        1.0      7      4  1949.0   
104613       4          0  Hot Water Rad  N        4.0     12      4  1940.0   
104614       2          1      Warm Cool  Y        1.0      8      4  1930.0   
104615       3          1  Hot Water Rad  Y        1.0      8      5  1940.0   
...        ...        ...            ... ..        ...    ...    ...     ...   
106434       3          2      Warm Cool  Y        1.0      9      4  1948.0   
106435       2          2      Warm Cool  Y        1.0      9      3  1936.0   
106436       3          1  Hot Water Rad  N        1.0     10      5  1934.0   
106437       2          1      Warm Cool  Y        1.0      8      3  1936.0   
106438       2          1      Warm Cool  Y        1.0      6      3  1941.0   
106439       3          1     Forced Air  Y        1.0      8      3  1951.0   
106440       3          1  Hot Water Rad  N        1.0      7      4  1935.0   
106441       3          1  Hot Water Rad  N        1.0     10      3  1934.0   
106442       4          1  Hot Water Rad  N        1.0      7      4  1934.0   
106443       3          1  Hot Water Rad  N        1.0     10      4  1936.0   
106444       5          2      Warm Cool  Y        1.0     16      7  1936.0   
106445       4          0  Hot Water Rad  N        1.0      9      4  1936.0   
106446       3          1      Warm Cool  Y        1.0      9      4  1936.0   
106447       3          1  Hot Water Rad  N        1.0      9      4  1936.0   
106448       4          0      Warm Cool  Y        1.0      8      5  1949.0   
106449       2          1      Warm Cool  Y        1.0      6      3  1936.0   
106450       4          1      Warm Cool  Y        1.0     11      5  1937.0   
106451       4          1      Warm Cool  Y        1.0     11      4  1940.0   
106452  

In [122]:
dcdf.loc[(dcdf['QUADRANT'].isnull()) & (dcdf['CITY'].isnull())]

BATHRM  HF_BATHRM           HEAT AC  NUM_UNITS  ROOMS  BEDRM     AYB  \
104610       2          0  Hot Water Rad  N        2.0     11      4  1938.0   

        YR_RMDL   EYB   ...     LONGITUDE ASSESSMENT_NBHD  ASSESSMENT_SUBNBHD  \
104610      NaN  1954   ...           NaN             NaN                 NaN   

       CENSUS_TRACT  CENSUS_BLOCK  WARD  SQUARE   X   Y QUADRANT  
104610          NaN           NaN   NaN    PAR  NaN NaN      NaN  

[1 rows x 48 columns]

In [124]:
dcdf.iloc[104610]

BATHRM                                  2
HF_BATHRM                               0
HEAT                        Hot Water Rad
AC                                      N
NUM_UNITS                               2
ROOMS                                  11
BEDRM                                   4
AYB                                  1938
YR_RMDL                               NaN
EYB                                  1954
STORIES                                 2
SALEDATE              2001-01-04 00:00:00
PRICE                                 NaN
QUALIFIED                               U
SALE_NUM                                1
GBA                                  2262
BLDG_NUM                                1
STYLE                             2 Story
STRUCT                              Multi
GRADE                             Average
CNDTN                             Average
EXTWALL                      Common Brick
ROOF                             Built Up
INTWALL                          H

In [128]:
# Drop the row with no address info
dcdfB = dcdf.drop(104610, axis=0)

In [129]:
dcdfB.loc[(dcdfB['QUADRANT'].isnull()) & (dcdfB['CITY'].isnull())]

Empty DataFrame
Columns: [BATHRM, HF_BATHRM, HEAT, AC, NUM_UNITS, ROOMS, BEDRM, AYB, YR_RMDL, EYB, STORIES, SALEDATE, PRICE, QUALIFIED, SALE_NUM, GBA, BLDG_NUM, STYLE, STRUCT, GRADE, CNDTN, EXTWALL, ROOF, INTWALL, KITCHENS, FIREPLACES, USECODE, LANDAREA, GIS_LAST_MOD_DTTM, SOURCE, CMPLX_NUM, LIVING_GBA, FULLADDRESS, CITY, STATE, ZIPCODE, NATIONALGRID, LATITUDE, LONGITUDE, ASSESSMENT_NBHD, ASSESSMENT_SUBNBHD, CENSUS_TRACT, CENSUS_BLOCK, WARD, SQUARE, X, Y, QUADRANT]
Index: []

[0 rows x 48 columns]

In [130]:
dcdfB["CITY"].fillna('WASHINGTON', inplace=True)

In [131]:
dcdfB["STATE"].fillna('DC', inplace=True)

In [132]:
dcdfB.count()

BATHRM                158956
HF_BATHRM             158956
HEAT                  158956
AC                    158956
NUM_UNITS             106695
ROOMS                 158956
BEDRM                 158956
AYB                   158685
YR_RMDL                80928
EYB                   158956
STORIES               106651
SALEDATE              132186
PRICE                  98216
QUALIFIED             158956
SALE_NUM              158956
GBA                   106695
BLDG_NUM              158956
STYLE                 106695
STRUCT                106695
GRADE                 106695
CNDTN                 106695
EXTWALL               106695
ROOF                  106695
INTWALL               106695
KITCHENS              106694
FIREPLACES            158956
USECODE               158956
LANDAREA              158956
GIS_LAST_MOD_DTTM     158956
SOURCE                158956
CMPLX_NUM              52261
LIVING_GBA             52261
FULLADDRESS           106040
CITY                  158956
STATE         

In [133]:
dcdfB['ZIPCODE'].unique()

array([20009., 20037., 20036., 20005., 20052., 20008., 20001., 20024.,
       20006., 20003., 20002., 20007., 20016., 20015., 20011., 20010.,
       20012., 20017., 20018., 20019., 20020., 20032., 20392., 20004.])

In [147]:
# changing AC zero to N

dcdfB.loc[dcdfB['AC']=='0', 'AC'] = 'N'
dcdfB['AC'].unique()

array(['Y', 'N'], dtype=object)

In [148]:
#Drop rows with lots of missing info - condition, ext wall, etc.
missing = dcdfB['NUM_UNITS'].isnull()
dcdfB.loc[missing]

BATHRM  HF_BATHRM        HEAT AC  NUM_UNITS  ROOMS  BEDRM     AYB  \
106696       2          0  Forced Air  Y        NaN      4      2  1911.0   
106697       2          0  Forced Air  Y        NaN      4      2  1911.0   
106698       2          0  Forced Air  Y        NaN      4      2  1911.0   
106699       2          0  Forced Air  Y        NaN      4      2  1911.0   
106700       2          0  Forced Air  Y        NaN      4      2  1911.0   
106701       2          0  Forced Air  Y        NaN      4      2  1911.0   
106702       2          0  Forced Air  Y        NaN      4      2  1911.0   
106703       2          0  Forced Air  Y        NaN      4      2  1911.0   
106704       2          0  Forced Air  Y        NaN      4      2  1911.0   
106705       2          0  Forced Air  Y        NaN      4      2  1911.0   
106706       2          0  Forced Air  Y        NaN      4      2  1911.0   
106707       2          0  Forced Air  Y        NaN      4      2  2007.0   
106708       2          0  Forced Air  Y        NaN      4      2  2007.0   
106709       2          0  Forced Air  Y        NaN      4      2  2007.0   
106710       2          0  Forced Air  Y        NaN      4      2  2007.0   
106711       2          0  Forced Air  Y        NaN      4      2  2007.0   
106712       2          0  Forced Air  Y        NaN      4      2  2007.0   
106713       2          0  Forced Air  Y        NaN      4      2  2007.0   
106714       1          0     Ht Pump  Y        NaN      4      2  1937.0   
106715       1          0     Ht Pump  Y        NaN      4      2  1937.0   
106716       1          0     Ht Pump  Y        NaN      4      2  1937.0   
106717       1          0     Ht Pump  Y        NaN      4      2  1937.0   
106718       1          1  Forced Air  Y        NaN      4      2  1937.0   
106719       1          1  Forced Air  Y        NaN      4      2  1937.0   
106720       1          0  Forced Air  Y        NaN      3      1  2004.0   
106721       1          0  Forced Air  Y        NaN      3      1  2004.0   
106722       1          0  Forced Air  Y        NaN      3      1  2004.0   
106723       1          0  Forced Air  Y        NaN      3      1  2004.0   
106724       1          0  Forced Air  Y        NaN      3      1  2004.0   
106725       1          0  Forced Air  Y        NaN      3      1  2004.0   
...        ...        ...         ... ..        ...    ...    ...     ...   
158927       2          0     Ht Pump  Y        NaN      6      3  1993.0   
158928       2          1     Ht Pump  Y        NaN      5      2  2013.0   
158929       2          1     Ht Pump  Y        NaN      5      2  2013.0   
158930       2          0  Forced Air  N        NaN      4      2  1900.0   
158931       2          1  Forced Air  N        NaN      4      2  1900.0   
158932       2          1  Forced Air  N        NaN      4      2  1900.0   
158933       2          0     Ht Pump  Y        NaN      4      2  1880.0   
158934       1          1     Ht Pump  Y        NaN      3      1  1880.0   
158935       1          0     Ht Pump  Y        NaN      3      1  1880.0   
158936       1          0     Ht Pump  Y        NaN      3      1  1880.0   
158937       1          0  Forced Air  Y        NaN      4      2  1992.0   
158938       2          0   Warm Cool  Y        NaN      7      4  1992.0   
158939       1          0  Forced Air  Y        NaN      4      2  1992.0   
158940       2          0  Forced Air  Y        NaN      7      4  1992.0   
158941       1          0  Forced Air  Y        NaN      4      2  1992.0   
158942       2          0  Forced Air  Y        NaN      7      4  1992.0   
158943       2          1  Forced Air  Y        NaN      5      2  2004.0   
158944       2          1  Forced Air  Y        NaN      5      2  2004.0   
158945       1          0  Forced Air  Y        NaN      3      1  1938.0   
158946       1          0  Forced Air  Y        NaN      4      2  1938.0   
1589

In [152]:
missing = ((dcdfB['NUM_UNITS'].isnull()) & dcdfB['CNDTN'].isnull())
dcdfB.loc[missing]
print ((dcdfB.loc[missing]).count())

BATHRM                52261
HF_BATHRM             52261
HEAT                  52261
AC                    52261
NUM_UNITS                 0
ROOMS                 52261
BEDRM                 52261
AYB                   52231
YR_RMDL               31649
EYB                   52261
STORIES                   0
SALEDATE              48004
PRICE                 40316
QUALIFIED             52261
SALE_NUM              52261
GBA                       0
BLDG_NUM              52261
STYLE                     0
STRUCT                    0
GRADE                     0
CNDTN                     0
EXTWALL                   0
ROOF                      0
INTWALL                   0
KITCHENS                  0
FIREPLACES            52261
USECODE               52261
LANDAREA              52261
GIS_LAST_MOD_DTTM     52261
SOURCE                52261
CMPLX_NUM             52261
LIVING_GBA            52261
FULLADDRESS               0
CITY                  52261
STATE                 52261
ZIPCODE             

In [153]:
dcdfC = dcdfB.dropna(subset=['NUM_UNITS'])

In [154]:
dcdfC.count()

BATHRM                106695
HF_BATHRM             106695
HEAT                  106695
AC                    106695
NUM_UNITS             106695
ROOMS                 106695
BEDRM                 106695
AYB                   106454
YR_RMDL                49279
EYB                   106695
STORIES               106651
SALEDATE               84182
PRICE                  57900
QUALIFIED             106695
SALE_NUM              106695
GBA                   106695
BLDG_NUM              106695
STYLE                 106695
STRUCT                106695
GRADE                 106695
CNDTN                 106695
EXTWALL               106695
ROOF                  106695
INTWALL               106695
KITCHENS              106694
FIREPLACES            106695
USECODE               106695
LANDAREA              106695
GIS_LAST_MOD_DTTM     106695
SOURCE                106695
CMPLX_NUM                  0
LIVING_GBA                 0
FULLADDRESS           106040
CITY                  106695
STATE         

In [155]:
# dealing with the empty kitchen record
dcdfC[dcdfC['KITCHENS'].isnull()]

BATHRM  HF_BATHRM        HEAT AC  NUM_UNITS  ROOMS  BEDRM     AYB  \
100629       2          1  Forced Air  Y        1.0      6      3  2016.0   

        YR_RMDL   EYB   ...     LONGITUDE ASSESSMENT_NBHD  \
100629      NaN  2017   ...    -76.972312  Randle Heights   

          ASSESSMENT_SUBNBHD CENSUS_TRACT  CENSUS_BLOCK    WARD  SQUARE  \
100629  043 A Randle Heights       7605.0   007605 2001  Ward 8    5627   

                X          Y QUADRANT  
100629 -76.973009  38.867576       SE  

[1 rows x 48 columns]

In [156]:
dcdfC.iloc[100629]

BATHRM                                   2
HF_BATHRM                                1
HEAT                            Forced Air
AC                                       Y
NUM_UNITS                                1
ROOMS                                    6
BEDRM                                    3
AYB                                   2016
YR_RMDL                                NaN
EYB                                   2017
STORIES                                  2
SALEDATE               2017-02-07 00:00:00
PRICE                               430000
QUALIFIED                                Q
SALE_NUM                                 3
GBA                                   2160
BLDG_NUM                                 1
STYLE                              2 Story
STRUCT                              Single
GRADE                        Above Average
CNDTN                                 Good
EXTWALL                       Vinyl Siding
ROOF                              Built Up
INTWALL    

In [157]:
dcdfC.loc[(dcdfC['AYB'] == 2016) & (dcdfC['ASSESSMENT_SUBNBHD'] == '043 A Randle Heights')]

BATHRM  HF_BATHRM        HEAT AC  NUM_UNITS  ROOMS  BEDRM     AYB  \
98235        3          1   Warm Cool  Y        1.0     13      3  2016.0   
100629       2          1  Forced Air  Y        1.0      6      3  2016.0   

        YR_RMDL   EYB   ...     LONGITUDE ASSESSMENT_NBHD  \
98235       NaN  2017   ...    -76.973452  Randle Heights   
100629      NaN  2017   ...    -76.972312  Randle Heights   

          ASSESSMENT_SUBNBHD CENSUS_TRACT  CENSUS_BLOCK    WARD  SQUARE  \
98235   043 A Randle Heights       7601.0   007601 2005  Ward 8    5590   
100629  043 A Randle Heights       7605.0   007605 2001  Ward 8    5627   

                X          Y QUADRANT  
98235  -76.974108  38.870110       SE  
100629 -76.973009  38.867576       SE  

[2 rows x 48 columns]

In [158]:
dcdfC.iloc[98235]

BATHRM                                   3
HF_BATHRM                                1
HEAT                             Warm Cool
AC                                       Y
NUM_UNITS                                1
ROOMS                                   13
BEDRM                                    3
AYB                                   2016
YR_RMDL                                NaN
EYB                                   2017
STORIES                                  2
SALEDATE               2015-12-17 00:00:00
PRICE                                  NaN
QUALIFIED                                U
SALE_NUM                                 3
GBA                                   4362
BLDG_NUM                                 1
STYLE                              2 Story
STRUCT                              Single
GRADE                        Above Average
CNDTN                                 Good
EXTWALL                       Vinyl Siding
ROOF                          Comp Shingle
INTWALL    

In [160]:
dcdfC["KITCHENS"].fillna("1", inplace=True)

In [161]:
dcdfC.count()

BATHRM                106695
HF_BATHRM             106695
HEAT                  106695
AC                    106695
NUM_UNITS             106695
ROOMS                 106695
BEDRM                 106695
AYB                   106454
YR_RMDL                49279
EYB                   106695
STORIES               106651
SALEDATE               84182
PRICE                  57900
QUALIFIED             106695
SALE_NUM              106695
GBA                   106695
BLDG_NUM              106695
STYLE                 106695
STRUCT                106695
GRADE                 106695
CNDTN                 106695
EXTWALL               106695
ROOF                  106695
INTWALL               106695
KITCHENS              106695
FIREPLACES            106695
USECODE               106695
LANDAREA              106695
GIS_LAST_MOD_DTTM     106695
SOURCE                106695
CMPLX_NUM                  0
LIVING_GBA                 0
FULLADDRESS           106040
CITY                  106695
STATE         

In [162]:
# Clean up grades
dcdfC['GRADE'].unique()

array(['Very Good', 'Above Average', 'Good Quality', 'Excellent',
       'Average', 'Superior', 'Fair Quality', 'Exceptional-D',
       'Exceptional-C', 'Low Quality', 'Exceptional-A', 'Exceptional-B',
       'No Data'], dtype=object)

In [163]:
dcdfC['GRADE'].value_counts()

Average          37356
Above Average    32101
Good Quality     20800
Very Good         8976
Excellent         3390
Superior          2634
Exceptional-A      818
Exceptional-B      278
Fair Quality       150
Exceptional-C       92
Exceptional-D       75
No Data             19
Low Quality          6
Name: GRADE, dtype: int64

In [164]:
# lump all exceptionals into one group, change Superior to Excellent, Above Average to Very Good, and Average to Good Quality, remove Quality from values

dcdfC.loc[dcdfC['GRADE']=='Exceptional-A', 'GRADE'] = 'Exceptional'
dcdfC.loc[dcdfC['GRADE']=='Exceptional-B', 'GRADE'] = 'Exceptional'
dcdfC.loc[dcdfC['GRADE']=='Exceptional-C', 'GRADE'] = 'Exceptional'
dcdfC.loc[dcdfC['GRADE']=='Exceptional-D', 'GRADE'] = 'Exceptional'
dcdfC.loc[dcdfC['GRADE']=='Superior', 'GRADE'] = 'Excellent'
dcdfC.loc[dcdfC['GRADE']=='Above Average', 'GRADE'] = 'Very Good'
dcdfC.loc[dcdfC['GRADE']=='Average', 'GRADE'] = 'Good Quality'
dcdfC.loc[dcdfC['GRADE']=='Good Quality', 'GRADE'] = 'Good'
dcdfC.loc[dcdfC['GRADE']=='Fair Quality', 'GRADE'] = 'Fair'
dcdfC.loc[dcdfC['GRADE']=='Low Quality', 'GRADE'] = 'Low'
dcdfC['GRADE'].unique()


/home/nbuser/anaconda3_501/lib/python3.6/site-packages/pandas/core/indexing.py:543: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s


array(['Very Good', 'Good', 'Excellent', 'Fair', 'Exceptional', 'Low',
       'No Data'], dtype=object)

In [172]:
# Map Grades to a number value

def GRADE_to_numeric(x):
    if x=='Low':
        return 1
    if x=='Fair':
        return 2
    if x=='Good':
        return 3
    if x=='Very Good':
        return 4
    if x=='Excellent':
        return 5
    if x=='Exceptional':
        return 0
    if x=='No Data':
        return 0
    
dcdfC['GRADE_NUM'] = dcdfC['GRADE'].apply(GRADE_to_numeric)
dcdfC.head()

/home/nbuser/anaconda3_501/lib/python3.6/site-packages/ipykernel/__main__.py:19: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy


BATHRM  HF_BATHRM           HEAT AC  NUM_UNITS  ROOMS  BEDRM     AYB  \
0       4          0      Warm Cool  Y        2.0      8      4  1910.0   
1       3          1      Warm Cool  Y        2.0     11      5  1898.0   
2       3          1  Hot Water Rad  Y        2.0      9      5  1910.0   
3       3          1  Hot Water Rad  Y        2.0      8      5  1900.0   
4       2          1      Warm Cool  Y        1.0     11      3  1913.0   

   YR_RMDL   EYB    ...     ASSESSMENT_NBHD ASSESSMENT_SUBNBHD  CENSUS_TRACT  \
0   1988.0  1972    ...          Old City 2   040 D Old City 2        4201.0   
1   2007.0  1972    ...          Old City 2   040 D Old City 2        4201.0   
2   2009.0  1984    ...          Old City 2   040 D Old City 2        4201.0   
3   2003.0  1984    ...          Old City 2   040 D Old City 2        4201.0   
4   2012.0  1985    ...          Old City 2   040 D Old City 2        4201.0   

  CENSUS_BLOCK    WARD  SQUARE          X          Y QUADRANT GRADE_NUM  
0  004201 2006  Ward 2     152 -77.040429  38.914881       NW         4  
1  004201 2006  Ward 2     152 -77.040429  38.914881       NW         4  
2  004201 2006  Ward 2     152 -77.040429  38.914881       NW         4  
3  004201 2006  Ward 2     152 -77.040429  38.914881       NW         4  
4  004201 2006  Ward 2     152 -77.040429  38.914881       NW         4  

[5 rows x 49 columns]

In [173]:
dcdfC['GRADE'].value_counts()

Good           58156
Very Good      41077
Excellent       6024
Exceptional     1263
Fair             150
No Data           19
Low                6
Name: GRADE, dtype: int64

In [174]:
dcdfC['GRADE_NUM'].value_counts()

3    58156
4    41077
5     6024
0     1282
2      150
1        6
Name: GRADE_NUM, dtype: int64

In [175]:
dcdf['EXTWALL'].value_counts()

Common Brick      81068
Brick/Siding       5569
Vinyl Siding       5290
Wood Siding        4540
Stucco             3216
Shingle            1181
Brick Veneer       1069
Aluminum            954
Stone               744
Brick/Stucco        673
Brick/Stone         626
Face Brick          512
Stone/Siding        339
Stone Veneer        254
Stone/Stucco        238
Hardboard           119
Concrete             82
Metal Siding         66
Concrete Block       54
Stucco Block         51
Default              32
Plywood              15
Adobe                 2
SPlaster              1
Rustic Log            1
Name: EXTWALL, dtype: int64

In [177]:
dcdfC['KITCHENS'].value_counts()

1.0     90435
2.0     11903
4.0      3051
3.0      1173
0.0       117
5.0        11
6.0         4
44.0        1
Name: KITCHENS, dtype: int64

In [184]:
# fix kitchens likely typo
dcdfC.loc[dcdfC['KITCHENS']=='4.0', 'KITCHENS'] = 4.0
dcdfC['KITCHENS'].unique()

array([2, 1, 3, 4, 5, 0, 6])

In [185]:
dcdfC['KITCHENS'].value_counts()

1    90435
2    11903
4     3052
3     1173
0      117
5       11
6        4
Name: KITCHENS, dtype: int64

In [186]:
dcdfC['FIREPLACES'].unique()

array([ 5,  4,  3,  0,  1,  2,  6,  7,  8, 12, 10, 13, 11,  9])

In [188]:
dcdfC.describe()

BATHRM      HF_BATHRM      NUM_UNITS          ROOMS  \
count  106695.000000  106695.000000  106695.000000  106695.000000   
mean        2.033104       0.607507       1.198032       7.382295   
std         1.062022       0.616418       0.596922       2.295571   
min         0.000000       0.000000       0.000000       0.000000   
25%         1.000000       0.000000       1.000000       6.000000   
50%         2.000000       1.000000       1.000000       7.000000   
75%         3.000000       1.000000       1.000000       8.000000   
max        14.000000      11.000000       6.000000      48.000000   

               BEDRM            AYB       YR_RMDL            EYB  \
count  106695.000000  106454.000000  49279.000000  106695.000000   
mean        3.368508    1933.888374   2000.900282    1966.204124   
std         1.100653      28.307436     17.415821      16.360212   
min         0.000000    1754.000000     20.000000    1900.000000   
25%         3.000000    1914.000000   1992.000000    1955.000000   
50%         3.000000    1930.000000   2006.000000    1964.000000   
75%         4.000000    1947.000000   2011.000000    1970.000000   
max        24.000000    2019.000000   2019.000000    2018.000000   

             STORIES         PRICE      ...             LANDAREA  CMPLX_NUM  \
count  106651.000000  5.790000e+04      ...        106695.000000        0.0   
mean        2.091794  5.799119e+05      ...          3416.592755        NaN   
std         2.933336  6.076454e+05      ...          5939.806004        NaN   
min         0.000000  1.000000e+00      ...             0.000000        NaN   
25%         2.000000  2.400000e+05      ...          1600.000000        NaN   
50%         2.000000  4.400000e+05      ...          2365.000000        NaN   
75%         2.000000  7.500000e+05      ...          4200.000000        NaN   
max       826.000000  2.510000e+07      ...        942632.000000        NaN   

       LIVING_GBA        ZIPCODE       LATITUDE      LONGITUDE   CENSUS_TRACT  \
count         0.0  106695.000000  106695.000000  106695.000000  106695.000000   
mean          NaN   20012.068110      38.916684     -77.010014    5555.761123   
std           NaN       7.678259       0.034774       0.043179    3503.401722   
min           NaN   20001.000000      38.819731     -77.113909     100.000000   
25%           NaN   20007.000000      38.892679     -77.035353    2002.000000   
50%           NaN   20011.000000      38.917736     -77.006218    6802.000000   
75%           NaN   20018.000000      38.944225     -76.982950    8804.000000   
max           NaN   20052.000000      38.995540     -76.909758   11100.000000   

                   X              Y      GRADE_NUM  
count  106459.000000  106459.000000  106695.000000  
mean      -77.010052      38.916673       3.460350  
std         0.043183       0.034726       0.713224  
min       -77.113135      38.820576       0.000000  
25%       -77.035283      38.892756       3.000000  
50%       -77.006329      38.917596       3.000000  
75%       -76.982970      38.944261       4.000000  
max       -76.910511      38.993646       5.000000  

[8 rows x 26 columns]

In [189]:
dcdfC['STORIES'].value_counts()

2.00      79356
3.00       9230
2.50       6105
1.00       4683
1.50       2291
2.25       2225
1.75       1175
1.25        452
2.75        444
4.00        375
3.50        109
0.00         43
9.00         36
2.70         28
3.25         20
3.75         15
2.20         13
5.00         11
6.00          7
25.00         4
1.70          4
2.30          3
7.00          2
4.50          2
275.00        2
3.70          2
4.75          1
250.00        1
0.75          1
43.00         1
826.00        1
3.20          1
8.25          1
65.00         1
0.25          1
0.50          1
2.33          1
1.34          1
20.00         1
12.00         1
Name: STORIES, dtype: int64

In [190]:
# Drop rows with bad stories
print (dcdfC.loc[(dcdfC['STORIES']==1.34)])
print (dcdfC.loc[(dcdfC['STORIES']==1.7)])
print (dcdfC.loc[(dcdfC['STORIES']==2.30)])
print (dcdfC.loc[(dcdfC['STORIES']==275)])
print (dcdfC.loc[(dcdfC['STORIES']==3.70)])
print (dcdfC.loc[(dcdfC['STORIES']==250)])
print (dcdfC.loc[(dcdfC['STORIES']==43)])
print (dcdfC.loc[(dcdfC['STORIES']==826)])
print (dcdfC.loc[(dcdfC['STORIES']==3.20)])
print (dcdfC.loc[(dcdfC['STORIES']==2.33)])
print (dcdfC.loc[(dcdfC['STORIES']==.25)])
print (dcdfC.loc[(dcdfC['STORIES']==.75)])
print (dcdfC.loc[(dcdfC['STORIES']==65.00)])
print (dcdfC.loc[(dcdfC['STORIES']==.50)])

       BATHRM  HF_BATHRM       HEAT AC  NUM_UNITS  ROOMS  BEDRM     AYB  \
95292       1          1  Warm Cool  Y        1.0      8      3  1940.0   

       YR_RMDL   EYB    ...     ASSESSMENT_NBHD ASSESSMENT_SUBNBHD  \
95292   2007.0  1975    ...           Hillcrest    028 C Hillcrest   

       CENSUS_TRACT CENSUS_BLOCK    WARD  SQUARE          X          Y  \
95292        7604.0  007604 2030  Ward 7    5669 -76.957494  38.864006   

      QUADRANT GRADE_NUM  
95292       SE         4  

[1 rows x 49 columns]
       BATHRM  HF_BATHRM           HEAT AC  NUM_UNITS  ROOMS  BEDRM     AYB  \
18702       1          0  Hot Water Rad  Y        1.0      2      1  1900.0   
19049       2          0  Hot Water Rad  N        1.0      8      4  1900.0   
19051       2          1      Warm Cool  Y        1.0      7      3  1900.0   
21300       1          2  Hot Water Rad  Y        1.0      6      2  1938.0   

       YR_RMDL   EYB    ...     ASSESSMENT_NBHD ASSESSMENT_SUBNBHD  \
18702      NaN  

In [191]:
# Drop the rows with bad stories data
dcdfC = dcdfC.drop(95292, axis=0)
dcdfC = dcdfC.drop(18702, axis=0)
dcdfC = dcdfC.drop(19049, axis=0)
dcdfC = dcdfC.drop(19051, axis=0)
dcdfC = dcdfC.drop(21300, axis=0)
dcdfC = dcdfC.drop(10948, axis=0)
dcdfC = dcdfC.drop(19874, axis=0)
dcdfC = dcdfC.drop(21317, axis=0)
dcdfC = dcdfC.drop(21170, axis=0)
dcdfC = dcdfC.drop(21930, axis=0)
dcdfC = dcdfC.drop(18619, axis=0)
dcdfC = dcdfC.drop(20189, axis=0)
dcdfC = dcdfC.drop(20491, axis=0)
dcdfC = dcdfC.drop(94741, axis=0)
dcdfC = dcdfC.drop(7546, axis=0)
dcdfC = dcdfC.drop(18736, axis=0)
dcdfC = dcdfC.drop(79235, axis=0)
dcdfC = dcdfC.drop(105278, axis=0)
dcdfC = dcdfC.drop(78344, axis=0)
dcdfC = dcdfC.drop(3737, axis=0)
dcdfC = dcdfC.drop(50484, axis=0)

In [192]:
dcdfC['STORIES'].value_counts()

2.00     79356
3.00      9230
2.50      6105
1.00      4683
1.50      2291
2.25      2225
1.75      1175
1.25       452
2.75       444
4.00       375
3.50       109
0.00        43
9.00        36
2.70        28
3.25        20
3.75        15
2.20        13
5.00        11
6.00         7
25.00        4
4.50         2
7.00         2
4.75         1
20.00        1
8.25         1
12.00        1
Name: STORIES, dtype: int64

In [209]:
dcdfC.loc[dcdfC['LANDAREA'] > 800000]


BATHRM  HF_BATHRM           HEAT AC  NUM_UNITS  ROOMS  BEDRM     AYB  \
34401       8          3  Hot Water Rad  Y        1.0     34      7  1927.0   

       YR_RMDL   EYB    ...     ASSESSMENT_NBHD ASSESSMENT_SUBNBHD  \
34401   2000.0  1998    ...     Rock Creek Park                NaN   

       CENSUS_TRACT CENSUS_BLOCK    WARD  SQUARE          X          Y  \
34401        1302.0  001302 3000  Ward 3    2248 -77.055808  38.947694   

      QUADRANT GRADE_NUM  
34401       NW         0  

[1 rows x 49 columns]

In [213]:
dcdfC.iloc[34400]

BATHRM                                  2
HF_BATHRM                               2
HEAT                        Hot Water Rad
AC                                      N
NUM_UNITS                               1
ROOMS                                   8
BEDRM                                   3
AYB                                  1937
YR_RMDL                              1987
EYB                                  1957
STORIES                                 2
SALEDATE                              NaN
PRICE                                 NaN
QUALIFIED                               U
SALE_NUM                                1
GBA                                  2027
BLDG_NUM                                1
STYLE                             2 Story
STRUCT                             Single
GRADE                                Good
CNDTN                                Good
EXTWALL                      Common Brick
ROOF                            Clay Tile
INTWALL                          H

In [217]:
dcdfC.iloc[34386]

BATHRM                                       8
HF_BATHRM                                    3
HEAT                             Hot Water Rad
AC                                           Y
NUM_UNITS                                    1
ROOMS                                       34
BEDRM                                        7
AYB                                       1927
YR_RMDL                                   2000
EYB                                       1998
STORIES                                   2.75
SALEDATE                   2009-10-05 00:00:00
PRICE                                      NaN
QUALIFIED                                    U
SALE_NUM                                     1
GBA                                      24030
BLDG_NUM                                     1
STYLE                                  3 Story
STRUCT                                  Single
GRADE                              Exceptional
CNDTN                                Very Good
EXTWALL      

In [218]:
dcdfC.count()

BATHRM                106674
HF_BATHRM             106674
HEAT                  106674
AC                    106674
NUM_UNITS             106674
ROOMS                 106674
BEDRM                 106674
AYB                   106433
YR_RMDL                49264
EYB                   106674
STORIES               106630
SALEDATE               84167
PRICE                  57888
QUALIFIED             106674
SALE_NUM              106674
GBA                   106674
BLDG_NUM              106674
STYLE                 106674
STRUCT                106674
GRADE                 106674
CNDTN                 106674
EXTWALL               106674
ROOF                  106674
INTWALL               106674
KITCHENS              106674
FIREPLACES            106674
USECODE               106674
LANDAREA              106674
GIS_LAST_MOD_DTTM     106674
SOURCE                106674
CMPLX_NUM                  0
LIVING_GBA                 0
FULLADDRESS           106019
CITY                  106674
STATE         

In [220]:
dcdfC.isnull().sum()

BATHRM                     0
HF_BATHRM                  0
HEAT                       0
AC                         0
NUM_UNITS                  0
ROOMS                      0
BEDRM                      0
AYB                      241
YR_RMDL                57410
EYB                        0
STORIES                   44
SALEDATE               22507
PRICE                  48786
QUALIFIED                  0
SALE_NUM                   0
GBA                        0
BLDG_NUM                   0
STYLE                      0
STRUCT                     0
GRADE                      0
CNDTN                      0
EXTWALL                    0
ROOF                       0
INTWALL                    0
KITCHENS                   0
FIREPLACES                 0
USECODE                    0
LANDAREA                   0
GIS_LAST_MOD_DTTM          0
SOURCE                     0
CMPLX_NUM             106674
LIVING_GBA            106674
FULLADDRESS              655
CITY                       0
STATE         